# Site Settings
title: Góc Làm Đẹp | Siêu Thị Mỹ Phẩm
email: doan.trong.quoc.binh@gmail.com
description: Hân hạnh chào đón bạn đến với Trang Web trực tuyến phục vụ khách hàng từ xa của chúng tôi.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://goclamdep.xyz" # the base hostname & protocol for your site
google_analytics: "UA-138771107-1"

# User Settings
username: Góc Làm Đẹp
user_description: Hotline 090 2683 189 | Fanpage https://www.facebook.com/AsiniceDung/
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
facebook_username: AsiniceDung
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#00CC33"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Giới Thiệu
    url: /about/
  - title: Liên Hệ
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
